// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/algorithm_service.proto
// Protobuf C++ Version: 5.29.0

#ifndef src_2falgorithm_5fservice_2eproto_2epb_2eh
#define src_2falgorithm_5fservice_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_src_2falgorithm_5fservice_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_src_2falgorithm_5fservice_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_src_2falgorithm_5fservice_2eproto;
namespace algorithm {
class AlgorithmRequest;
struct AlgorithmRequestDefaultTypeInternal;
extern AlgorithmRequestDefaultTypeInternal _AlgorithmRequest_default_instance_;
class AlgorithmResponse;
struct AlgorithmResponseDefaultTypeInternal;
extern AlgorithmResponseDefaultTypeInternal _AlgorithmResponse_default_instance_;
}  // namespace algorithm
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace algorithm {

// ===================================================================


// -------------------------------------------------------------------

class AlgorithmResponse final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:algorithm.AlgorithmResponse) */ {
 public:
  inline AlgorithmResponse() : AlgorithmResponse(nullptr) {}
  ~AlgorithmResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AlgorithmResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AlgorithmResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AlgorithmResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline AlgorithmResponse(const AlgorithmResponse& from) : AlgorithmResponse(nullptr, from) {}
  inline AlgorithmResponse(AlgorithmResponse&& from) noexcept
      : AlgorithmResponse(nullptr, std::move(from)) {}
  inline AlgorithmResponse& operator=(const AlgorithmResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline AlgorithmResponse& operator=(AlgorithmResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AlgorithmResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const AlgorithmResponse* internal_default_instance() {
    return reinterpret_cast<const AlgorithmResponse*>(
        &_AlgorithmResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(AlgorithmResponse& a, AlgorithmResponse& b) { a.Swap(&b); }
  inline void Swap(AlgorithmResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AlgorithmResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AlgorithmResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AlgorithmResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AlgorithmResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AlgorithmResponse& from) { AlgorithmResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AlgorithmResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "algorithm.AlgorithmResponse"; }

 protected:
  explicit AlgorithmResponse(::google::protobuf::Arena* arena);
  AlgorithmResponse(::google::protobuf::Arena* arena, const AlgorithmResponse& from);
  AlgorithmResponse(::google::protobuf::Arena* arena, AlgorithmResponse&& from) noexcept
      : AlgorithmResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kJsonOutputFieldNumber = 1,
  };
  // string json_output = 1;
  void clear_json_output() ;
  const std::string& json_output() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_json_output(Arg_&& arg, Args_... args);
  std::string* mutable_json_output();
  PROTOBUF_NODISCARD std::string* release_json_output();
  void set_allocated_json_output(std::string* value);

  private:
  const std::string& _internal_json_output() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_json_output(
      const std::string& value);
  std::string* _internal_mutable_json_output();

  public:
  // @@protoc_insertion_point(class_scope:algorithm.AlgorithmResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      47, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AlgorithmResponse& from_msg);
    ::google::protobuf::internal::ArenaStringPtr json_output_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_src_2falgorithm_5fservice_2eproto;
};
// -------------------------------------------------------------------

class AlgorithmRequest final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:algorithm.AlgorithmRequest) */ {
 public:
  inline AlgorithmRequest() : AlgorithmRequest(nullptr) {}
  ~AlgorithmRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AlgorithmRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AlgorithmRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AlgorithmRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline AlgorithmRequest(const AlgorithmRequest& from) : AlgorithmRequest(nullptr, from) {}
  inline AlgorithmRequest(AlgorithmRequest&& from) noexcept
      : AlgorithmRequest(nullptr, std::move(from)) {}
  inline AlgorithmRequest& operator=(const AlgorithmRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AlgorithmRequest& operator=(AlgorithmRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AlgorithmRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AlgorithmRequest* internal_default_instance() {
    return reinterpret_cast<const AlgorithmRequest*>(
        &_AlgorithmRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AlgorithmRequest& a, AlgorithmRequest& b) { a.Swap(&b); }
  inline void Swap(AlgorithmRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AlgorithmRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AlgorithmRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AlgorithmRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AlgorithmRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AlgorithmRequest& from) { AlgorithmRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AlgorithmRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "algorithm.AlgorithmRequest"; }

 protected:
  explicit AlgorithmRequest(::google::protobuf::Arena* arena);
  AlgorithmRequest(::google::protobuf::Arena* arena, const AlgorithmRequest& from);
  AlgorithmRequest(::google::protobuf::Arena* arena, AlgorithmRequest&& from) noexcept
      : AlgorithmRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kJsonInputFieldNumber = 1,
  };
  // string json_input = 1;
  void clear_json_input() ;
  const std::string& json_input() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_json_input(Arg_&& arg, Args_... args);
  std::string* mutable_json_input();
  PROTOBUF_NODISCARD std::string* release_json_input();
  void set_allocated_json_input(std::string* value);

  private:
  const std::string& _internal_json_input() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_json_input(
      const std::string& value);
  std::string* _internal_mutable_json_input();

  public:
  // @@protoc_insertion_point(class_scope:algorithm.AlgorithmRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      45, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AlgorithmRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr json_input_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_src_2falgorithm_5fservice_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AlgorithmRequest

// string json_input = 1;
inline void AlgorithmRequest::clear_json_input() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.json_input_.ClearToEmpty();
}
inline const std::string& AlgorithmRequest::json_input() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:algorithm.AlgorithmRequest.json_input)
  return _internal_json_input();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AlgorithmRequest::set_json_input(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.json_input_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:algorithm.AlgorithmRequest.json_input)
}
inline std::string* AlgorithmRequest::mutable_json_input() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_json_input();
  // @@protoc_insertion_point(field_mutable:algorithm.AlgorithmRequest.json_input)
  return _s;
}
inline const std::string& AlgorithmRequest::_internal_json_input() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.json_input_.Get();
}
inline void AlgorithmRequest::_internal_set_json_input(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.json_input_.Set(value, GetArena());
}
inline std::string* AlgorithmRequest::_internal_mutable_json_input() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.json_input_.Mutable( GetArena());
}
inline std::string* AlgorithmRequest::release_json_input() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:algorithm.AlgorithmRequest.json_input)
  return _impl_.json_input_.Release();
}
inline void AlgorithmRequest::set_allocated_json_input(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.json_input_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.json_input_.IsDefault()) {
    _impl_.json_input_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:algorithm.AlgorithmRequest.json_input)
}

// -------------------------------------------------------------------

// AlgorithmResponse

// string json_output = 1;
inline void AlgorithmResponse::clear_json_output() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.json_output_.ClearToEmpty();
}
inline const std::string& AlgorithmResponse::json_output() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:algorithm.AlgorithmResponse.json_output)
  return _internal_json_output();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AlgorithmResponse::set_json_output(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.json_output_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:algorithm.AlgorithmResponse.json_output)
}
inline std::string* AlgorithmResponse::mutable_json_output() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_json_output();
  // @@protoc_insertion_point(field_mutable:algorithm.AlgorithmResponse.json_output)
  return _s;
}
inline const std::string& AlgorithmResponse::_internal_json_output() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.json_output_.Get();
}
inline void AlgorithmResponse::_internal_set_json_output(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.json_output_.Set(value, GetArena());
}
inline std::string* AlgorithmResponse::_internal_mutable_json_output() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.json_output_.Mutable( GetArena());
}
inline std::string* AlgorithmResponse::release_json_output() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:algorithm.AlgorithmResponse.json_output)
  return _impl_.json_output_.Release();
}
inline void AlgorithmResponse::set_allocated_json_output(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.json_output_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.json_output_.IsDefault()) {
    _impl_.json_output_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:algorithm.AlgorithmResponse.json_output)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace algorithm


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // src_2falgorithm_5fservice_2eproto_2epb_2eh
